{% set name = "flashgeotext" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 99d2e525725701e62d25eed7afe9d948b707f0c4fb6647749a5e929f6050d5b4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - flashtext >=2.7,<3.0
    - loguru >=0.5.3,<0.6.0
    - pip
    - poetry-core >=1.0.0,<2.0.0
    - pydantic >=1.8,<2.0
    - python >=3.6
  run:
    - flashtext >=2.7,<3.0
    - loguru >=0.5.3,<0.6.0
    - pydantic >=1.8,<2.0
    - python >=3.6

test:
  imports:
    - flashgeotext

about:
  home: "https://flashgeotext.iwpnd.pw"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Extract and count countries and cities (+their synonyms) from text"
  doc_url: https://flashgeotext.iwpnd.pw
  dev_url: https://github.com/iwpnd/flashgeotext

extra:
  recipe-maintainers:
    - iwpnd
    - francbartoli
